// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNt3AJbUUb4qutwsS24qYuR8erBLtV70g',
    appId: '1:626459525476:web:a788cbd341de28b176fa71',
    messagingSenderId: '626459525476',
    projectId: 'meal-app-7021e',
    authDomain: 'meal-app-7021e.firebaseapp.com',
    storageBucket: 'meal-app-7021e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwaj_YusJ2RI1EkqcMqv5Tm-V4TyzQFVE',
    appId: '1:626459525476:android:dd9ee659366fddb676fa71',
    messagingSenderId: '626459525476',
    projectId: 'meal-app-7021e',
    storageBucket: 'meal-app-7021e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc90TwLx9L6rKPGZYU0ipbfcsF_2Us7NQ',
    appId: '1:626459525476:ios:197d69bfcf6d8e6d76fa71',
    messagingSenderId: '626459525476',
    projectId: 'meal-app-7021e',
    storageBucket: 'meal-app-7021e.firebasestorage.app',
    iosBundleId: 'com.example.lab02Mis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc90TwLx9L6rKPGZYU0ipbfcsF_2Us7NQ',
    appId: '1:626459525476:ios:197d69bfcf6d8e6d76fa71',
    messagingSenderId: '626459525476',
    projectId: 'meal-app-7021e',
    storageBucket: 'meal-app-7021e.firebasestorage.app',
    iosBundleId: 'com.example.lab02Mis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNt3AJbUUb4qutwsS24qYuR8erBLtV70g',
    appId: '1:626459525476:web:a8538653e89568a076fa71',
    messagingSenderId: '626459525476',
    projectId: 'meal-app-7021e',
    authDomain: 'meal-app-7021e.firebaseapp.com',
    storageBucket: 'meal-app-7021e.firebasestorage.app',
  );
}
